---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "exporter.name" . }}
    chart: {{ template "exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "exporter.fullname" . }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: 80
      targetPort: 8080
      protocol: TCP
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app: {{ template "exporter.name" . }}
    release: {{ .Release.Name }}
