---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "exporter.fullname" . }}-config
  labels:
    app: {{ template "exporter.name" . }}
    chart: {{ template "exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  config: {{ toYaml .Values.config | b64enc }}
