{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.serviceAccountName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
{{- with .Values.labels }}{{ toYaml . | nindent 4 }}{{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "app.serviceAccountName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
{{- with .Values.labels }}{{ toYaml . | nindent 4 }}{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRole}}
subjects:
- kind: ServiceAccount
  name: {{ template "app.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}